# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9a4288c5687ed7a04a1745de822782b69fb8bf45d4111926d7d10ee0618639968a369545079ee81492b47cf66f89f1b3aa8606ab9d8ae0d983f4510b5918ef3c

test:
  secret_key_base: 8c02e94ee1d512eed6fdce8d7f88f34726d4c5619fe32ee7934e443b7c6adb7496d4e2e0c6fd3b3c953e4838dc9d0bcaca37e3a08e9be6b1c7a02a600a85f48b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
